### ISSUE TITLE
dotenv setup.

### ISSUE THREAD

**Issue by piotrleniec** [piotrleniec/sendit#2]
[dotenv](https://github.com/bkeepers/dotenv) provides an easy way to securely use credentials in rails projects. We need it to securely use Facebook configuration.

**Comment by dimon-k** [comment]
Dotenv was set up in the following PR: https://github.com/piotrleniec/sendit/pull/7

**Comment by piotrleniec** [comment]
I've requested changes on the PR #7.

**Comment by dimon-k** [comment]
Fixed and already Merged!
