### ISSUE TITLE
PostgreSQL database configuration.

### ISSUE THREAD

**Issue by piotrleniec** [piotrleniec/sendit#3]
In order to allow users to use Facebook authentication, we need to configure our application to use PostgreSQL database. Devise stores users in a database even when they're authenticated by an external service. It's also important to mention that we need configuration only for `test` and `development` environments because Heroku automatically injects its production database configuration.

**Comment by dimon-k** [comment]
PostgreSQL was set up in the following PR: https://github.com/piotrleniec/sendit/pull/6

**Comment by piotrleniec** [comment]
I've approved the PR. :+1:

**Comment by dimon-k** [comment]
Merged!
